FROM node:22-slim as builder

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build || (cat /root/.npm/_logs/*-debug.log && exit 1)

FROM node:22-slim as runner

WORKDIR /app
COPY --from=builder /app/build ./build
COPY --from=builder /app/package*.json ./
RUN npm ci --only=production

EXPOSE 3000
CMD ["npm", "run", "start"]