name: Deploy Docs
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install
        working-directory: ./acdocs

      - name: Build the site
        run: yarn build
        working-directory: ./acdocs

      - name: Deploy to GitHub Pages
        run: yarn deploy
        working-directory: ./acdocs
        env:
          GIT_USER: akka-cache-robot
          GITHUB_TOKEN: ${{ secrets.AKKA_CACHE_ROBOT_REPO_TOKEN }}
