name: Deploy Docs
on:
  push:
    branches: [ main ]

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    
      permissions:
        pages: write
        id-token: write
        
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
          
        - uses: actions/setup-node@v4
          with:
            node-version: 22
            cache: yarn
            cache-dependency-path: ./acdocs/yarn.lock
  
        - name: Install dependencies
          run: yarn install --frozen-lockfile
          working-directory: ./acdocs
          
        - name: Build website
          run: yarn build 
          working-directory: ./acdocs

        - name: Deploy website
          run: |
            git config --global user.name "akka-cache-robot"
            echo "machine github.com login akka-cache-robot password ${{ secrets.AKKA_CACHE_ROBOT_REPO_TOKEN }} " > ~/.netrc
            yarn install && GIT_USER=akka-cache-robot yarn run publish-gh-pages
          working-directory: ./acdocs
          env:
            GITHUB_TOKEN: ${{ secrets.AKKA_CACHE_ROBOT_REPO_TOKEN }} 



            
