name: Deploy Docs
on:
  push:
    branches: [ main ]

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
        
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
          
        - uses: actions/setup-node@v4
          with:
            node-version: 22
            cache: yarn
            cache-dependency-path: ./acdocs/yarn.lock
  
        - name: Install dependencies
          run: yarn install --frozen-lockfile
          working-directory: ./acdocs
          
        - name: Build website
          run: yarn build 
          working-directory: ./acdocs

        - name: Deploy website
          run: |
            git config --global user.email "akka-cache-robot@akka.io"
            git config --global user.name "akka-cache-robot"
            GIT_USER='akka-cache-robot' GIT_PASS='${{ secrets.AKKA_CACHE_ROBOT_REPO_TOKEN }}' yarn deploy
          working-directory: ./acdocs
          env:
            GIT_PASS: ${{ secrets.AKKA_CACHE_ROBOT_REPO_TOKEN }} 



            
