name: Deploy Docs
on:
  push:
    branches: [ main ]

jobs:
    build-and-deploy-docs:
      runs-on: ubuntu-latest
        
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
          
        - uses: actions/setup-node@v4
          with:
            node-version: 22
            cache: yarn
            cache-dependency-path: ./acdocs/yarn.lock
  
        - name: Install dependencies
          run: yarn install
          working-directory: ./acdocs
          
        - name: Build website
          run: yarn build 
          working-directory: ./acdocs

        - name: Deploy website
          run: |
            eval "$(ssh-agent -s)"
            echo $SCP_SECRET | base64 -di > /tmp/id_rsa
            chmod 600 /tmp/id_rsa
            ssh-add /tmp/id_rsa
            export RSYNC_RSH="ssh -o StrictHostKeyChecking=no"
            rsync -azP -r build/* akkarepo@gustav.akka.io:www/cache
          working-directory: ./acdocs
          env:
            SCP_SECRET: ${{ secrets.AKKA_RSYNC_GUSTAV }}
